services:
  ai-service:
    build: .

    container_name: work-ai-service

    privileged: true

    network_mode: host

    devices:
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1

    volumes:
      - ./:/app

    environment:
      - PYTHONUNBUFFERED=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    command: python3 src/main.py