services:
  ai-service:
    build: .
    container_name: work-ai-service
    restart: "no"
    privileged: true

    volumes:
      - ./:/app

    devices:
      - /dev/video0:/dev/video0

    ports:
      - "8000:8000"

    environment:
      - PYTHONUNBUFFERED=1

    command: python src/main.py